### ISSUE TITLE
Deleting collection in shared folder

### ISSUE THREAD

**Issue by rbhargava2** [tracek/gee_asset_manager#20]
Hey Lucas, 
I was wondering if we could use the geebam tool to delete collection from a shared folder, just like we could upload using the -p switch. Currently it doesn't seem to work, perhaps, it would be a good idea to add that functionality for delete tool as well.

Thanks.

**Comment by tracek** [comment]
Hey,

Can you try the dev branch and post the error you are getting? I removed the concept of relative path, so you always need to provide full path. Somewhat more typing, but less confusion = good. Plus cleaner code. 

Also, mind that it might be not possible to delete a shared asset if you are not the owner. Also, some systems would require that you stop sharing it first (can't say how it works on GEE).

Let me know - thanks!

**Comment by rbhargava2** [comment]
Hey,

Here is the error I got: 
![image](https://cloud.githubusercontent.com/assets/23130293/20943762/ac079832-bbb5-11e6-9799-0448c8f8026e.png)

I am able to delete shared assets in the folder though. 
Thanks!

**Comment by tracek** [comment]
Are you sure you're on "develop" branch? If so, then for sure the old version is lurking around and should be removed manually. The piece of code it is complaining about was removed in develop branch,

**Comment by rbhargava2** [comment]
Hey Lucas, 
I am sure I am in the develop branch. Should I remove the following snippet from the geebam.py ? 
if 'users' not in id:
        root_path_in_gee = ee.data.getAssetRoots()[0]['id']
        id = root_path_in_gee + '/' + id

**Comment by tracek** [comment]
The snippet you pasted is not present on develop branch, but in batch_remover.py https://github.com/tracek/gee_asset_manager/blob/master/geebam/batch_remover.py#L34 Also, the version seen in the error message matches master, not develop (which is 0.1.3).

**Comment by rbhargava2** [comment]
Hey Lucas, 
that makes sense. But i get the message that I am on develop branch but it doesn't seem so:

C:\Python27\Scripts\gee_asset_manager>git checkout develop
M       geebam/geebam.py
Already on 'develop'
Your branch is up-to-date with 'origin/develop'.

C:\Python27\Scripts\gee_asset_manager>cd..

C:\Python27\Scripts>geebam delete projects/servir-mekong/ET_DATA
2016-12-07 17:39:27,387 :: oauth2client.transport :: INFO :: Attempting refresh to obtain initial access_token
2016-12-07 17:39:27,387 :: oauth2client.client :: INFO :: Refreshing access_token
2016-12-07 17:39:30,500 :: root :: INFO :: Attempting to delete collection projects/servir-mekong/ET_DATA
Traceback (most recent call last):
  File "C:\Python27\Scripts\geebam-script.py", line 11, in <module>
    load_entry_point('geebam==0.1.0', 'console_scripts', 'geebam')()
  File "C:\Python27\lib\site-packages\geebam\geebam.py", line 84, in main
    args.func(args)
  File "C:\Python27\lib\site-packages\geebam\geebam.py", line 50, in delete_collection_from_parser
    delete_collection(args.id)
  File "C:\Python27\lib\site-packages\geebam\geebam.py", line 26, in delete_collection
    items_in_collection = ee.data.getList(params)
  File "C:\Python27\lib\site-packages\ee\data.py", line 172, in getList
    return send_('/list', params)
  File "C:\Python27\lib\site-packages\ee\data.py", line 730, in send_
    raise ee_exception.EEException(json_content['error']['message'])
ee.ee_exception.EEException: No such folder or collection: 'users/radb06/projects/servir-mekong/ET_DATA'.

**Comment by tracek** [comment]
Now you're getting a different error than initially reported. Previously you were getting AttributeError, while here it complains that there is no such asset. However, by the path it's clear that it assumes a "relative" path, i.e. wrt your home. This functionality is not present neither on develop nor master. Please make sure that the tool is removed before you install it again. Check:

* site-packages
* bin 

On Windows you can use `where` command, equivalent of `which` on Linux.

Mind that you can run `geebam` without installing it - just `python geebam.py delete stuff`.

**Comment by tracek** [comment]
I am closing the issue due to lack of activity. Feel free to re-open.
