### ISSUE TITLE
Incorrect credentials

### ISSUE THREAD

**Issue by blackpegas** [tracek/gee_asset_manager#27]
Hi Lukasz,

May be it is an easy to fix issue. I am new to all that coding stuff. I was trying to upload .tif images to GEE. However I receive an error message saying "Incorrect credentials". But I really do not understand what does that mean and what should I do. Could you please explain?

Here is what I get :
D:\>python -m geebam upload -u valerija.stepanova@gmail.
com --source "D:\Berkely\Mag\Data\MOD16\d\prmtr" --dest users/Hydrology_Ass_3_la
b/MOD16
2017-04-13 16:54:09,229 :: oauth2client.transport :: INFO :: Attempting refresh
to obtain initial access_token
2017-04-13 16:54:09,244 :: oauth2client.client :: INFO :: Refreshing access_toke
n
Password:
2017-04-13 16:54:18,213 :: root :: WARNING :: Collection users/Hydrology_Ass_3_l
ab/MOD16 already exists
2017-04-13 16:54:19,319 :: root :: INFO :: Processing image 1 out of 180: D:\Ber
kely\Mag\Data\MOD16\d\prmtr\MOD16A2.A2000001.ET_1km.tif
2017-04-13 16:54:20,084 :: root :: ERROR :: Incorrect credentials. Probably. If
you are sure the credentials are OK, refresh the authentication token. If it did
 not work report a problem. They might have changed something in the Matrix.

Thank you in advance for your help. 

Valerija

**Comment by tracek** [comment]
Hi Valerija,

Let's check the basics. Apologies if some of these will sound too obvious:

1. Check that your credentials are OK. Simply login to Google with your browser. You can also just type your password someplace in clear text to make sure that it is correct (sometimes keyboard layout can be different than expected if you are working on a remote machine).
2. Move someplace your EE credentials and authorise anew. You can find their location with e.g. python -c "import ee; print(ee.oauth.get_credentials_path())"
3. Update to the latest geebam (latest on main) and earthengine-api.

What Python version are you running?

**Comment by blackpegas** [comment]
Hi Lukasz,

Thank you for your reply. 
1. The password I am using is Ok (have checked it), however I can't print it in when there is a request from geebam.
2. I have updated credential file, but there is no result, and the way it is recommended to check if it is working is functioning properly
3. I just installed geebam and earthengine-api yesterday. And reinstalled geebam and earthengine-api today. Same thing.
4. My Python version is 2.7.10

(Since I am a new to all that stuff, I downloaded your folder manually (from here https://github.com/tracek/gee_asset_manager), and than installed it using `cd D:\gee_asset_manager-master && python -m pip install geebam` And it was written that all requirements are satisfied after the installation.

I am running geebam using following line python `-m geebam upload -u valerija.stepanova@gmail.com --source D:\Berkely\Mag\Data\MOD16\d\data_reproj --dest users/Hydrology_Ass_3_lab/MOD` , but I don't think it is an issue)

Best,
Valerija

**Comment by tracek** [comment]
Thanks! Do me a favour and run it as: python ./geebam.py (rest of the stuff) in the directory where you have the tool.

If you have checked that the password works on the same machine in a browser, then everything should be fine. The tool takes care that the password is not stored or displayed anywhere.

Didn't work? Let's try debugging together.

Here's a snippet that isolates the problem. Long story short, it parses Google login page and authenticates you:

```python
import sys
import requests
from bs4 import BeautifulSoup

if sys.version_info > (3, 0):
    from urllib.parse import unquote
else:
    from urllib import unquote

google_accounts_url = 'https://accounts.google.com'
authentication_url = 'https://accounts.google.com/ServiceLoginAuth'

session = requests.session()

login_html = session.get(google_accounts_url)
soup_login = BeautifulSoup(login_html.content, 'html.parser').find('form').find_all('input')
payload = {}
for u in soup_login:
    if u.has_attr('value'):
        payload[u['name']] = u['value']

payload['Email'] = raw_input("Enter your email: ")
payload['Passwd'] = raw_input("Enter your password (WARNING! GOES IN CLEAR TEXT!!!): ")

auto = login_html.headers.get('X-Auto-Login')
follow_up = unquote(unquote(auto)).split('continue=')[-1]
galx = login_html.cookies['GALX']

payload['continue'] = follow_up
payload['GALX'] = galx

session.post(authentication_url, data=payload)

_ = session.get('https://ee-api.appspot.com/assets/upload/geturl?')
r = session.get('https://ee-api.appspot.com/assets/upload/geturl?')

print(r.text)
```

Please send the response to my email.

I'd recommend to run this code in interactive session, so that you can easily inspect content of the response of `session.get`. Do you run it inside academic network? If so, can you try on your home computer? Reason is that sometimes network firewall can prevent such traffic.

**Comment by blackpegas** [comment]
Dear Lukasz,

Million thank you fro your kindness and sorry for my stupidity. I have tried one more time making sure I am in the needed directory with the tool and typing in password attentively and everything worked. Probably was mistyping password.. was confused that nothing was shown there.  Now the upload have started, have some problems with the file names (I have dots in it, but It should not be a problem to change the names of the files).
Thank you again!
Have a nice day!

Best,
Valerija

**Comment by tracek** [comment]
I am happy that it worked for you! If handling files with dots in the name is an issue, please do report it as an issue. The tool should work with any allowed file name. No need to rename your files, let me handle it. I will close this one.

**Comment by blackpegas** [comment]
I figured out what was the problem. I had phone verification on and apparently that was causing a problem. I have switched it off and tried to load the program after your first e-mail, but it seems it didn't work. But by the time I have started to run it after your second e-mail it was off and worked.
I thought about it only today and verified it. Just wanted to let you know, so if someone else would have the same issue.

Thank you again for all your help.

Best,
Valerija

**Comment by marcusspiegel** [comment]
I am having the Incorrect Credentials problem as above and have tried all the solutions suggested in this and other threads. When I tried the snippet that isolates the problem, I also get the following error:
`Traceback (most recent call last):
  File "testAuth.py", line 28, in <module>
    galx = login_html.cookies['GALX']
  File "C:\Python27\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Python27\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='GALX', domain=None, path=None"`

Do you have any idea what might be causing this? Thanks.
