### ISSUE TITLE
Problems authenticating with Google

### ISSUE THREAD

**Issue by jelisejev** [tracek/gee_asset_manager#29]
Hi, 

I'm trying to use gee_asset_manager to automatically upload processed assets and I've encountered some problems with Google authentication. Although I'm working in my [own fork](https://github.com/ctco-dev/gee_asset_manager) which supports non-interactive authentication, I can also reproduce the problem in the main version as well. Here's the problem:

- I tried to upload the assets in the test folder from my personal machine using my personal account with this command `python geebam.py upload -u jelisejev.p@gmail.com --source tests/images --dest users/jelisejevp/Geebam/TestCollection10`. It worked. However, when I try to run it on a remote VM, authentication fails with the following error: `RROR :: Incorrect credentials. Probably. If you are sure the credentials are OK, refresh t
he authentication token. If it did not work report a problem. They might have changed something in the Matrix.`. I've explicitly allowed access from this machine from my google account settings, but this didn't help.
- When I tried to do this with a new test Google account, I got the same error from both my mac and the VM. The new account has access to Google Earth Engine and the credentials are correct.

Any idea what could be the problem? Could this be some clever security feature of Google?

**Comment by tracek** [comment]
Hey.

"Nope" to the security feature, at least not this time. I used your fork and after a slight tweak (batch_uploader:95 - your change works under assumption that the folder exists; if not you will get an error) I could upload some images. Which Python are you using?

Check #27 for a code snippet that allows you easily to reproduce the problem. Put the password in open text to make sure there are no issues. More importantly - are you using two-factor authentication? If so, that might be your issue, as in the referenced issue. 

BTW - nice idea with adding support for service accounts.

**Comment by jelisejev** [comment]
Hey @tracek 

I've tried reproducing the problem with the code snippet you suggested. I was able to login with my personal account, however, for the test account, it outputs Google's login page. Two-factor authentication is disabled for the test account. I'm using python 2.7.10.

> I used your fork and after a slight tweak (batch_uploader:95 - your change works under assumption that the folder exists; if not you will get an error) 

Yes, this change was intentional since the original implementation does not allow to upload to a top-level directory for a personal bucket using a service account. It checks write permissions for the parent folder and the personal root folder is never writable for a service account.

**Comment by tracek** [comment]
Gotcha. I am glad it works for a standard user. I never tested it or intended to work with service accounts, to which you don't login as to normal accounts; it's no surprise that it does not work. Mind that this tool is relatively fragile, as it's not using officially supported GEE functionality. If you're trying to build any sort of service, then I would strongly suggest using Google Cloud API. I will put a note on a README. 

Thanks!
Lucas

**Comment by jelisejev** [comment]
Not exactly. What I meant is that there are two authentications going on: one with the google account to upload files to the cloud storage and one with GEE to transfer them from the storage to GEE assets. Authentication with GEE using a service account works fine. But authentication fails in most of the cases. So far I've tried:
1. logging in from my private mac with my personal Google email - works;
2. logging in from a vm with the same personal Google email - doesn't work
3. logging in from my private mac with a new Google email - doesn't work
4. logging in from a vm with a new Google email - doesn't work

So it works differently even for the same account but from different origins. 

You mean for this to work in a stable manner we should upload files to the cloud storage using the API?

**Comment by jelisejev** [comment]
@tracek FYI, I've added the option to upload files directly to project GCS bucket using a service account. Now both authentications are working using the same service account and pk. Would you be interested in merging these changes into master? https://github.com/tracek/gee_asset_manager/compare/master...ctco-dev:master

**Comment by tracek** [comment]
Thanks a lot! My apologies for the lack of response on the thread. To answer your question: yes, cloud storage API is the way to go if you are looking for stability, so your GCS feature is very much what you need. Reason is simple: it's what Google is officially supporting. 

The "direct" way involves parsing a web site and using some tricks to get it uploaded. It's very useful if for any reason you can't or don't want to use GCS. If you can, it's a better choice.
