### ISSUE TITLE
GALX cookie

### ISSUE THREAD

**Issue by geosconsulting** [tracek/gee_asset_manager#36]
I have used geebam for quite a few months now and suddenly in every machine where ti is installed I get an error related with the line:
 galx = login_html.cookies['GALX']

It seems that google authentication is not returning that cookie anymore.

**Comment by doctorluz** [comment]
Hi Lucas! I am also having a problem with the GALX cookie...
I'm running the batch uploader in a docker machine in which I have no problems authenticating to GEE,

But when I run the upload command I get this sequence of errors:

  File "/usr/local/bin/geebam", line 9, in <module>
    load_entry_point('geebam', 'console_scripts', 'geebam')()
  File "/usr/local/src/gee_asset_manager/geebam.py", line 65, in main
    args.func(args)
  File "/usr/local/src/gee_asset_manager/geebam.py", line 35, in upload_from_parser
    nodata_value=args.nodata)
  File "/usr/local/src/gee_asset_manager/gee_asset_manager/batch_uploader.py", line 55, in upload
    google_session = __get_google_auth_session(user, password)
  File "/usr/local/src/gee_asset_manager/gee_asset_manager/batch_uploader.py", line 186, in __get_google_auth_session
    galx = login_html.cookies['GALX']
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 327, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 398, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='GALX', domain=None, path=None"

Appears to be the same error as above...

**Comment by samapriya** [comment]
This is a quick fix is comment out the two lines with galx in the batch_uploader.py and it seems to work after that, I understand that the script might use galx to set cookies which are being used after sometime but I uploaded about 100 assets to check if it break and it seems to be working. Would still be great to understand what changed. Thanks Lucas

**Comment by aignatius** [comment]
We've been frustrated with this error the last few days, as well. Thanks for the suggestion, samapriya!

**Comment by geosconsulting** [comment]
Thanks Samapriya your amendments to the original code work just fine.
I have noticed that the only cookie returned now is named GAPS with no trace og the one named GALX.

**Comment by tracek** [comment]
Thanks everyone. Kudos to @samapriya for the workaround. I don't seem to be getting any cookie nowadays. For now I just removed handling of cookies, although it remains to be seen if upload of large volumes of assets remains unaffected.
