### ISSUE TITLE
Image Band Name

### ISSUE THREAD

**Issue by nazmussazib** [tracek/gee_asset_manager#38]
I am using geebam for uploading a  large number of images where each of the image has 5 bands.
The GEE took default band names (e.g., b1, b2) but I want to provide different band names instead of those default . I have found that earthengine has a command line option to provide band names separately
but not noticed in the geebam. Is there any way to provide band names using geebam?
Thanks a lot.

**Comment by tracek** [comment]
Hey - not currently, but adding such a feature shouldn't be a trouble. Can you send my way a few images with a few bands? Do let me know as well how would you like to provide the band names. Command line option?

**Comment by nazmussazib** [comment]
Hi, the tool is really useful, thanks for developing this tool. I attach sample images where each of them contains 5 raster files. I want to provide the band names as an argument in the geebam function. 
[Sample_data.zip](https://github.com/tracek/gee_asset_manager/files/1315533/Sample_data.zip)

**Comment by tracek** [comment]
Hey - I am glad you find it useful. Have a look at the develop branch and let me know if it works for you.

**Comment by nazmussazib** [comment]
Hi, it works perfectly, Thanks much!

**Comment by tracek** [comment]
Great, I just merged into the main branch.
