### ISSUE TITLE
pip install requirement file

### ISSUE THREAD

**Issue by DapperMapper14** [tracek/gee_asset_manager#4]
Hi,

I'd like to use this tool to manage asset for my GEE account but am running into some issues with the pip install.  I get the following error after following your instructions on install:

`You must give at least one requirement to install (see "pip help install")`

I tried the --allow-all-external and --allow-unverified but it looks like these functions have been deprecated.  Do you have any suggestions?

Thanks!

Jon

**Comment by tracek** [comment]
Hi,

Can you paste here how exactly are you running the installation? My suspicion is that you are missing the dot in the command, i.e. doing: `pip install` instead of `pip install .` in the root directory of the program. Let me know if it helped!

Cheers,
Lucas

**Comment by DapperMapper14** [comment]
That did the trick!  Missed the period in the documentation.

Thanks!

Jon

**Comment by tracek** [comment]
Great! Shout if I can help further.
