### ISSUE TITLE
Incorrect credentials issue when uploading directory directly to GEE Assets

### ISSUE THREAD

**Issue by ZunyiXie** [tracek/gee_asset_manager#40]
#Thanks very much for this tool. Everything seemed to work well for me except that I couldn’t upload a directory to GEE Assets due to the issue below after I typed the password. I am pretty sure I input the correct password and tried many times but always got the same error. Any suggestions? Thanks!

“2017–11–02 18:08:31,628 :: root :: ERROR :: Incorrect credentials. Probably. If you are sure the credentials are OK,  #ref
resh the authentication token. If it did not work report a problem. They might have changed something in the Matrix.”

Cheers

Joey

**Comment by tracek** [comment]
Hey,

Thanks for reporting! Can you share an archive with the directory you wanted to upload? It would also help if you could tell me more about your environment (OS, Python, anything special?). Also, please make sure you don't have two-factor authentication enabled.

Cheers,
Lukasz

**Comment by ZunyiXie** [comment]
Sorry for the late reply. 

I am using Windows 10 (Education) with Anaconda Python 2.7.13 (64-bit).

Two-factor authentication is not enabled for my gmail account and I also turned on the "less secure apps".

My command on Command Prompt is 
"geebam upload -u zunyixie@gmail.com --source "E:/GRACE" --dest "users/zunyixie/GRACE_Img_Collection"

Every time after I input the password, I will get the "Incorrect credentials error" below.

![image](https://user-images.githubusercontent.com/3301641/32420048-82940530-c2d0-11e7-9dcc-08c35cf86454.png)

I am having the last try via Google Service account as below, but still wait for google earth engine to approve my account. 

geebam upload -s 179237509489-compute@developer.gserviceaccount.com -k "C:/Users/uqzxie1/Google Drive/Google_Earth_Engine/Moudles/privatekey.json" --source "E:/GRACE" --dest "users/zunyixie/GRACE_Img_Collection"

I will keep you updated after my service account gets approved.

Thanks for your help!

Cheers

Joey

**Comment by ZunyiXie** [comment]
Hi Lucasz,

Please close this issue as I believe this should be my single unlucky issue.

I had my last try on my Windows desktop at home, and found exactly the same error saying 'Incorrect Credentials', then I started suspecting my gmail account.

I registered a new gmail account and used it to apply a new GEE, then try geebam/geeadd again, it worked!!!!!! I used my current gmail to register GEE in 2014 but never used it until recently. I had no problem of logging in GEE using this email but have no idea why it has no credential to access my GEE given that I have made all the settings like earthengine authenticate etc.

Now I will upload data to this new gmail account and share the data with my old one, where I stored all my testing scripts.

Sorry for the hassle, and thanks for trying to help.

Cheers

Joey

**Comment by tracek** [comment]
Hi Joey,

Many thanks for coming back with this information. Unsurprisingly, I could not figure out what could be wrong, because, as usual, "it works our end". Since it's not uncommon problem, I will create a troubleshooting guide on what to check first. I am glad it worked for you ultimately! 

Cheers,
Lukasz

**Comment by ZunyiXie** [comment]
Hi Lukasz,

Thanks very much for your geebam, which runs like magic now.

Cheers

Joey
