### ISSUE TITLE
GEE Complains with "Unable to open ..." message

### ISSUE THREAD

**Issue by herrtunante** [tracek/gee_asset_manager#43]
Hi Lukasz,

I am trying to upload a new collection to my assets and I am getting this error that I cannot figure out.

When I run the upload command it all works well and I get no error but in the task frame of GEE ui I see that all of the running tasks have failed (in red) with the message:

> Error: Unable to open 8c7b9b47f57bec71bd52709834db171ebae0d3c08e1a6482cf8aff88.tif.

I tried uploading the same images directly from the Asset manager in GEE and it works fine. Any ideas?
The TIF are not specially large (around 200 KB)

The same command with the same files used now worked a week ago...any ideas?

> geebam upload -u user@gmail.com -m "C:\temp\properties.csv" --source "C:\temp\data" --dest users/MY_USER/test

Thanks!

**Comment by tracek** [comment]
Hi @herrtunante !

Interesting. I have not changed anything, any API changes would not affect this part. Can you copy the data from command line to the folder from which you are running the command? If that works, can you then try to upload, just specify "." as source?

I guess the message is message is essentially: Error: Unable to open [file name], right? It's not the same every time?

Cheers,
Lukasz

**Comment by herrtunante** [comment]
Hi tried your solution but it did not work.

However I tried using a different user and it worked fine... I don't quite understand the issue (same command being sent with all the same parameters except for username) but in the meantime I will just stick to this other user.

Thanks for the support.

**Comment by tracek** [comment]
Strange indeed. It seems like somehow the first user does not have _read_ permissions on the files. Yet it manages to copy the data... I will close the issue for now as it does not seem to be related with the tool. Feel free to reopen if anything indicates otherwise. 

Good luck!
