### ISSUE TITLE
understanding Image Upload

### ISSUE THREAD

**Issue by rbhargava2** [tracek/gee_asset_manager#8]
Hi Lucas,
 Thank you so much for your help via email! I just joined GitHub and thought of sharing my problem here so that others can access your suggestion too after that I have another question I would like to ask you. 

My problem was that I was getting an error saying bs4 module not found, to solve it, I just used pip to installed bs4 and it worked. (pip install bs4)

Another problem I ran into was after starting the image upload. For now, I am just trying it with one test image. While the run created an image collection in EE successfully, it was empty and my image didn't get uploaded.

Here is the message I saw on the console: 
C:\Python27\Scripts>geebam upload -u radb.06@gmail.com -d C:\ET_Data\test_upload -m C:\ET_Data\test_upload\test_metadata.csv
2016-10-28 17:08:31,469 :: oauth2client.transport :: INFO :: Attempting refresh to obtain initial access_token
2016-10-28 17:08:31,470 :: oauth2client.client :: INFO :: Refreshing access_token
Password:
2016-10-28 17:08:37,868 :: requests.packages.urllib3.connectionpool :: INFO :: Starting new HTTPS connection (1): accounts.google.com
2016-10-28 17:08:38,657 :: requests.packages.urllib3.connectionpool :: INFO :: Starting new HTTPS connection (1): accounts.google.co.in
2016-10-28 17:08:38,940 :: requests.packages.urllib3.connectionpool :: INFO :: Starting new HTTPS connection (1): myaccount.google.com
2016-10-28 17:08:41,674 :: root :: INFO :: New collection users/radb06/test_upload created
2016-10-28 17:08:41,677 :: root :: INFO :: Processing image 1 out of 1: C:\ET_Data\test_upload\ETensemble250m-h27v6-mm-Monthly-2003_01.tif
2016-10-28 17:08:42,306 :: requests.packages.urllib3.connectionpool :: INFO :: Starting new HTTPS connection (1): ee-api.appspot.com
2016-10-28 17:08:42,528 :: requests.packages.urllib3.connectionpool :: INFO :: Starting new HTTPS connection (1): www.google.com
2016-10-28 17:08:42,835 :: requests.packages.urllib3.connectionpool :: INFO :: Starting new HTTPS connection (1): appengine.google.com

Do you know what am I missing here? 
Thank you is much for your help throughout,
Really appreciate it!

**Comment by rbhargava2** [comment]
Also, Is there a way to upload my images not to my users/ folder but to a shared assets folder I have access to. The thing is, I have very limited space in my folder but our lab has enough space in the shared folder and I would like to just use that. I understand if it is not possible to upload it in the shared folder, I can either use credentials for the lab account and upload it there or I could as GEE to increase  my space quota. It would just be convenient to upload it from my account, so I was wondering. 
Thanks again!

**Comment by tracek** [comment]
Hi there,

I made a separate issue from your second comment. By Monday it should be implemented on the develop branch.

Can you share more information about the error you are reporting? I would appreciate sending me error log (assuming it's not empty). Even better option is sharing with me your data: the image and associated metadata.

**Comment by rbhargava2** [comment]
[test_gee_upload.zip](https://github.com/tracek/gee_asset_manager/files/560361/test_gee_upload.zip)

Hello,
Please find the folder with one of my files and .csv metadata file. Just a background, I converted NetCDFs to GeoTIFFs using arcpy and the other file types you see for that one image was an output from the same. 
I wasn't sure how to send you the error log. What I posted is all I output was on cmd. I wish I could provide more info but I hope sharing the data and metadata would help you take a look at it first hand. 

Thanks for your help again and I am so sorry for not paying much attention earlier and miss-speling your name! I am really sorry, Lukasz!

**Comment by tracek** [comment]
No worries about the name, I haven't even noticed. After years abroad I am used to all sort of combinations :).

The updated tool now should be more vocal on exceptions. However, in your case it wouldn't be of any help, since I am not checking whether whether the ingestion task succeed. And if it failed - what was the reason? Sounds like a nice feature.

Anyway, if you check *tasks* on [GEE Playground](https://code.earthengine.google.com/) you will see why it failed: 

> Error: Unable to determine projection for the input file. 

You want to get a "proper" GeoTIFF. Check [this](http://gis.stackexchange.com/questions/87642/how-to-convert-a-tif-with-tfw-to-a-geotiff) answer on StackExchange. Let me know if it worked.

**Comment by rbhargava2** [comment]
Hey Lukasz!
I just defined the projection of my tiff in ArcMap and the upload worked. Here is a link of the image in a test folder. 
https://code.earthengine.google.com/?asset=users/radb06/test_upload 

Thank you so much for bearing with my questions! I was wondering if the other issue (ingesting image collection on a shared folder\uploading images in the shared folder) has been posted?

**Comment by tracek** [comment]
Excellent, I will close the issue then.

Upload to a shared folder is in already (issue #9) - let me know if it works for you.
